// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxttrmfhatmgelvyjuip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4dHRybWZoYXRtZ2VsdnlqdWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzY5MzksImV4cCI6MjA2Mzg1MjkzOX0.5BIa1cVtGz5yHu2SYwvrdjDXcZ_za02C3f4dHj0QMZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);